### ISSUE TITLE
gRPC API/v2

### ISSUE THREAD

**Issue by carlobortolan** [joschahenningsen/TUM-Live#1415]
**Is your feature request related to a problem? Please describe.**
Currently, GoCast is built on top of a REST API written in Go using the Gin web framework. However, this API is unversioned and, therefore, can't be really used by external services (e.g., the Campus App, Artemis, a future TUM-Live App, etc.).

**Describe the solution you'd like**
A new, **versioned** gRPC API called `api_v2` which allows for external services (e.g., TUM Campus App, future GoCast App, etc.) to integrate lecture videos and features with a stable API.   
While not immediately relevant, gRPC would also have the benefit of other features such as bi-directional streaming or better performance compared to HTTP/REST.

**Describe alternatives you've considered**
Keep the current system as is.

**Additional context**
This issue is used to keep an overview of the progress with the new API:

#### User-related endpoint groups:
- [x] Implement users endpoints (#1429)
- [x] Implement courses endpoints (#1429)
- [x] Implement notification endpoints (#1492)
- [x] Implement stream endpoints (#1495)
- [x] Implement bookmarks endpoints (#1492)
- [x] Implement progress endpoints (#1495)

#### Lecturer-related endpoint groups:
- [ ] Will be implemented in a separate future issue if necessary

> [!note]
> A prototype was developed last year for the iPraktikum GoCast app (see [this PR draft](https://github.com/TUM-Dev/gocast/pull/1279)) but has not been updated since then. To avoid changing the API used for the GoCast app and avoid having one very large commit, I'd implement each endpoint group as one and to incrementally add merge them to the production system.
