### ISSUE TITLE
Add "bulk actions" to stream management

### ISSUE THREAD

**Issue by joschahenningsen** [joschahenningsen/TUM-Live#190]
Editing streams can currently only be done one stream at a time. It would be nice to have a checkbox next to every stream in the admin tab and be able to apply bulk actions. 
E.g. or now: select multiple streams and click on a `delete selected` button instead of deleting them one by one.

**Todo:**
- [ ] #194
- [ ] Update titles
- [ ] Change lecture hall
- [ ] change start/end time
- [ ] move to day of week

@mono424 this might be something for now because streaming on the test server is not yet possible :)

**Comment by mono424** [comment]
Sounds good I will start with that. Will take the other task when streaming is working, and it can be tested :)
